### ISSUE TITLE
Unable to open file 'model_data/yolo_weights.h5'

### ISSUE THREAD

**Issue by deaffella** [pythonlessons/YOLOv3-object-detection-tutorial#15]
Hi! I'm trying to train a yolo model in google colab. 
I successfully downloaded the dataset and converted it to xml in colab, but when I try to run the script train.py or train_bottleneck.py I get an error:
`Traceback (most recent call last):

  File "train_bottleneck.py", line 224, in <module>
    _main()
  File "train_bottleneck.py", line 30, in _main
    freeze_body=2, weights_path='model_data/yolo_weights.h5') # make sure you know what you freeze
  File "train_bottleneck.py", line 143, in create_model
    model_body.load_weights(weights_path, by_name=True, skip_mismatch=True)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/topology.py", line 2647, in load_weights
    with h5py.File(filepath, mode='r') as f:
  File "/usr/local/lib/python3.6/dist-packages/h5py/_hl/files.py", line 312, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/usr/local/lib/python3.6/dist-packages/h5py/_hl/files.py", line 142, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = 'model_data/yolo_weights.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)`

Please help me. What should I do?

**Comment by deaffella** [comment]
Sorry.
I just forgot to convert the model to yolo format
