### ISSUE TITLE
Value Error while running either train.py or train_bottleneck.py

### ISSUE THREAD

**Issue by AbhinavKoul** [pythonlessons/YOLOv3-object-detection-tutorial#17]
ValueError: Tensor("conv2d_1/kernel:0", shape=(3, 3, 3, 32), dtype=float32_ref) must be from the same graph as Tensor("input_1:0", shape=(?, ?, ?, 3), dtype=float32).

FULL STACK 

Using TensorFlow backend.
2020-04-09 19:37:20.094175: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
WARNING:tensorflow:From C:\Users\abhin\Anaconda3\lib\site-packages\tensorflow_core\python\compat\v2_compat.py:88: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
Traceback (most recent call last):
  File "train_bottleneck.py", line 223, in <module>
    _main()
  File "train_bottleneck.py", line 29, in _main
    model, bottleneck_model, last_layer_model = create_model(input_shape, anchors, num_classes,freeze_body=2, weights_path='model_data/yolo_weights.h5') # make sure you know what you freeze
  File "train_bottleneck.py", line 138, in create_model
    model_body = yolo_body(image_input, num_anchors//3, num_classes)
  File "E:\Projects\YOLO Live Detection\YOLOv3-custom-training\yolo3\model.py", line 72, in yolo_body
    darknet = Model(inputs, darknet_body(inputs))
  File "E:\Projects\YOLO Live Detection\YOLOv3-custom-training\yolo3\model.py", line 48, in darknet_body
    x = DarknetConv2D_BN_Leaky(32, (3,3))(x)
  File "E:\Projects\YOLO Live Detection\YOLOv3-custom-training\yolo3\utils.py", line 17, in <lambda>
    return reduce(lambda f, g: lambda *a, **kw: g(f(*a, **kw)), funcs)
  File "E:\Projects\YOLO Live Detection\YOLOv3-custom-training\yolo3\utils.py", line 17, in <lambda>
    return reduce(lambda f, g: lambda *a, **kw: g(f(*a, **kw)), funcs)
  File "C:\Users\abhin\Anaconda3\lib\site-packages\keras\engine\topology.py", line 619, in __call__
    output = self.call(inputs, **kwargs)
  File "C:\Users\abhin\Anaconda3\lib\site-packages\keras\layers\convolutional.py", line 168, in call
    dilation_rate=self.dilation_rate)
  File "C:\Users\abhin\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py", line 3338, in conv2d
    data_format=tf_data_format)
  File "C:\Users\abhin\Anaconda3\lib\site-packages\tensorflow_core\python\ops\nn_ops.py", line 899, in convolution
    name=name)
  File "C:\Users\abhin\Anaconda3\lib\site-packages\tensorflow_core\python\ops\nn_ops.py", line 991, in convolution_internal
    with ops.name_scope(name, scope, [input, filters]) as name:
  File "C:\Users\abhin\Anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py", line 6237, in __enter__
    g_from_inputs = _get_graph_from_inputs(self._values)
  File "C:\Users\abhin\Anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py", line 5883, in _get_graph_from_inputs
    _assert_same_graph(original_graph_element, graph_element)
  File "C:\Users\abhin\Anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py", line 5818, in _assert_same_graph
    (item, original_item))
ValueError: Tensor("conv2d_1/kernel:0", shape=(3, 3, 3, 32), dtype=float32_ref) must be from the same graph as Tensor("input_1:0", shape=(?, ?, ?, 3), dtype=float32)

**Comment by pythonlessons** [comment]
Try to reduce batch size

**Comment by AbhinavKoul** [comment]
thanks, it worked
