### ISSUE TITLE
realtime_detect.py - AttributeError: 'MSS' object has no attribute '_srcdc'

### ISSUE THREAD

**Issue by rahairi** [pythonlessons/YOLOv3-object-detection-tutorial#4]
Tried your realtime_detect.py after training, got this error 

Traceback (most recent call last):

  File "C:\Users\User\Anaconda2\envs\pythonGPU\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Users\User\Anaconda2\envs\pythonGPU\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\User\Desktop\deep-learning\YOLOv3-object-detection-tutorial-master\YOLOv3-custom-training\realtime_detect.py", line 184, in GRABMSS_screen
    img = np.array(sct.grab(monitor))
  File "C:\Users\User\Anaconda2\envs\pythonGPU\lib\site-packages\mss\windows.py", line 283, in grab
    self._bmp = self.gdi32.CreateCompatibleBitmap(self._srcdc, width, height)
AttributeError: 'MSS' object has no attribute '_srcdc'

**Comment by pythonlessons** [comment]
Did you found what was wrong ?
